name: poc-ros-zenoh

x-environment: &environment
    environment:
      RUST_LOG: ${RUST_LOG:-trace}

services:
  zenoh-router:
    <<: *environment
    profiles:
      - run
    image: ubuntu:24.04
    entrypoint: >
      /bin/bash -c "
      /usr/bin/router
      "
    network_mode: host
    volumes:
      - .././target/release/router:/usr/bin/router:rw

  zenoh-bridge:
    <<: *environment
    profiles:
      - run
    image: eclipse/zenoh-bridge-ros2dds:latest
    command: "-c bridge-config.json5"
    network_mode: host
    volumes:
      - ../bridge-config.json5:/bridge-config.json5:ro
    depends_on:
      zenoh-router:
        condition: service_started

  turtle-sim:
    <<: *environment
    environment:
      DISPLAY: "192.168.0.2:0.0"
      RMW_IMPLEMENTATION: rmw_cyclonedds_cpp
    profiles:
      - run
    build:
      dockerfile: ros-turtlesim.Dockerfile
      context: .
    command: bash -c "source /opt/ros/rolling/setup.bash && ros2 run turtlesim turtlesim_node"
    network_mode: host
    volumes:
      - ../bridge-config.json5:/bridge-config.json5:ro
      - /tmp/.X11-unix/:/tmp/.X11-unix:rw
    depends_on:
      zenoh-router:
        condition: service_started
      zenoh-bridge:
        condition: service_started

  rpc-client:
    <<: *environment
    environment:
      RPC_SERVER_ADDR: "localhost:7000"
    profiles:
      - run
    image: ubuntu:22.04
    entrypoint: > 
      /bin/bash -c "
      sleep 1 &&
      /usr/bin/client
      "
    network_mode: host
    expose:
      - 7000
    volumes:
      - .././target/release/client:/usr/bin/client:rw
    depends_on:
      zenoh-router:
        condition: service_started
    tty: true
    stdin_open: true

  build:
    profiles:
      - build-ros
    build:
      context: .
      dockerfile: builder-ros.Dockerfile
    volumes:
      - ../.:/app:rw
    entrypoint: /app/docker/entrypoint-dev.sh
    working_dir: /app
    command: "cargo build --release"
  
  dev:
    profiles:
      - build-ros
    build:
      context: .
      dockerfile: builder-ros.Dockerfile
    volumes:
      - ../.:/app:rw
    entrypoint: /app/docker/entrypoint-dev.sh
    working_dir: /app
    command: "cargo watch -x check -x clippy -x build"

